apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":"2023-06-05T18:41:04Z","generation":1,"name":"dfaas-webide-deployment","namespace":"default","resourceVersion":"1006440","uid":"cb2ad1af-7f9d-4ea7-9485-92b2e8e274a3"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"dfaas-webide"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"dfaas-webide"}},"spec":{"containers":[{"env":[{"name":"MONGODB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mongodb-root-password","name":"my-mongodb"}}},{"name":"FUNCTION_NAME","value":"write_test_topic"},{"name":"MONGODB_HOST","value":"my-mongodb.default.svc.cluster.local"},{"name":"MONGODB_PORT","value":"27017"},{"name":"MONGODB_USER","value":"root"}],"image":"danroblewis/dfaas-webide:latest","imagePullPolicy":"Always","name":"dfaas-webide","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2023-06-05T18:41:04Z","lastUpdateTime":"2023-06-05T18:41:09Z","message":"ReplicaSet \"dfaas-webide-deployment-555749dd5b\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2023-06-09T04:10:20Z","lastUpdateTime":"2023-06-09T04:10:20Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2023-06-05T18:41:04Z"
  generation: 3
  name: dfaas-webide-deployment
  namespace: default
  resourceVersion: "3682670"
  uid: cb2ad1af-7f9d-4ea7-9485-92b2e8e274a3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dfaas-webide
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dfaas-webide
    spec:
      containers:
      - env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: my-mongodb
        - name: FUNCTION_NAME
          value: write_test_topic
        - name: MONGODB_HOST
          value: my-mongodb.default.svc.cluster.local
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USER
          value: root
        - name: KAFKA_ADDRESS
          value: my-kafka-0.my-kafka-headless.default.svc.cluster.local:9092
        image: danroblewis/dfaas-webide:latest
        imagePullPolicy: Always
        name: dfaas-webide
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: dfaas-webide
      serviceAccountName: dfaas-webide
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-05T18:41:04Z"
    lastUpdateTime: "2023-06-09T04:47:03Z"
    message: ReplicaSet "dfaas-webide-deployment-c5c79b588" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-28T18:44:44Z"
    lastUpdateTime: "2023-06-28T18:44:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
